### ISSUE TITLE
Application instance initialized with different loop

### ISSUE THREAD

**Issue by ChuckGl** [ChuckGl/tfbrew#1]
Under Raspian 11 (Bullseye) 23-DEC-2023 release I am getting a runtime error (see below). I believe it is due to changes in the aiohttp library.  The original tfbew worked as late at April 2023.  The error message indicates that the web application instance was initialized with a different event loop than the one currently being used.

python3 tfbrew.py 
Using config from config.yaml
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-4' coro=<_run_app() done, defined at /home/pi/.local/lib/python3.9/site-packages/aiohttp/web.py:303> exception=RuntimeError('web.Application instance initialized with different loop')>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web.py", line 544, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web.py", line 357, in _run_app
    await runner.setup()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 295, in setup
    self._server = await self._make_server()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 398, in _make_server
    self._app._set_loop(loop)
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web_app.py", line 262, in _set_loop
    raise RuntimeError(
RuntimeError: web.Application instance initialized with different loop
Traceback (most recent call last):
  File "/home/pi/tfbrew/tfbrew.py", line 81, in <module>
    web.run_app(app, port=config.get('port',8080))
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web.py", line 544, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web.py", line 357, in _run_app
    await runner.setup()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 295, in setup
    self._server = await self._make_server()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 398, in _make_server
    self._app._set_loop(loop)
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/web_app.py", line 262, in _set_loop
    raise RuntimeError(
RuntimeError: web.Application instance initialized with different loop

**Comment by ChuckGl** [comment]
Updated tfbrew.py and common.py.  These changes ensure that both tfbrew.py and common.py are using the same event loop instance, resolving the RuntimeError related to different event loop initialization.

**Comment by ChuckGl** [comment]
Updated tfbrew.py and common.py.  These changes ensure that both tfbrew.py and common.py are using the same event loop instance, resolving the RuntimeError related to different event loop initialization.
